# Stalwart Mail Server initial configuration
# This file will be used to initialize the Stalwart mail server
# It configures automated settings for contact@batchshots.com

[server]
hostname = "mail.batchshots.com"

# Proxy settings - required for working with Traefik
[server.proxy]
trusted-networks = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "127.0.0.1/32"]

# HTTP listener for admin panel
[server.listener.http]
bind = "[::]:8080"
protocol = "http"

# HTTPS listener
[server.listener.https]
bind = "[::]:443"
protocol = "http"
tls.implicit = true
proxy.override = true

# SMTP listener
[server.listener.smtp]
bind = "[::]:25"
protocol = "smtp"
proxy.override = true

# Submission listener (587)
[server.listener.submission]
bind = "[::]:587"
protocol = "smtp"
proxy.override = true

# Submissions listener (465)
[server.listener.submissions]
bind = "[::]:465"
protocol = "smtp"
tls.implicit = true
proxy.override = true

# IMAP listener
[server.listener.imap]
bind = "[::]:143"
protocol = "imap"
proxy.override = true

# IMAPS listener
[server.listener.imaps]
bind = "[::]:993"
protocol = "imap"
tls.implicit = true
proxy.override = true

# ManageSieve listener
[server.listener.manage-sieve]
bind = "[::]:4190"
protocol = "manage-sieve"
proxy.override = true

# Directory and authentication settings
[directory]
type = "internal"

# Auto-configured account settings
[autoconfig]
# This section will be processed when the container starts
# to automatically create the contact@batchshots.com account
[[autoconfig.accounts]]
email = "contact@batchshots.com"
password = "AUTO_GENERATE"  # The startup script will replace this with a random password

# Default domain configuration
[[directory.domains]]
name = "batchshots.com"
primary = true

# TLS settings
[certificate.default]
default = true 