# Certificate Resolvers are responsible for retrieving certificates from an ACME server
# See https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
certificatesResolvers:
  letsEncrypt:
    acme:
      email: "andriifedorenko@gmail.com"  # Email address used for registration
      storage: "/letsencrypt/acme.json"    # File or key used for certificates storage
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: "30"
#      httpChallenge:
#        entryPoint: web
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsEncrypt

# Docker configuration backend
providers:
  swarm:
    exposedByDefault: false
    watch: true
    network: batchshots
ping: {}
# API and dashboard configuration
api:
  insecure: true
  dashboard: true
  debug: true

accesslog: true

log:
  level: DEBUG
